version: 1
formatters:
  logfile:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%m/%d/%Y %H:%M:%S %p'
  console:
    format: '%(asctime)s %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console 
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    filename: history.log
    level: DEBUG
    formatter: logfile 
loggers:
  panacompra:
    level: INFO 
    handlers: [console,file]
    propagate: no
  PanaCrawler:
    level: DEBUG
    handlers: [console,file]
    propagate: no
  Worker:
    level: DEBUG
    handlers: [file]
    propagate: no
  Scraper:
    level: DEBUG
    handlers: [file,console]
    propagate: no
  DB:
    level: DEBUG
    handlers: [file]
    propagate: no
  mrclean:
    level: DEBUG
    handlers: [file]
    propagate: no




